<?php

namespace FactelBundle\Entity\Repository;

/**
 * ProformaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProformaRepository extends \Doctrine\ORM\EntityRepository {

    public function cantidadProformas($idEstablecimiento, $idEmisor) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select("COUNT(proforma.id)")
                ->from("FactelBundle:Proforma", "proforma");
        if ($idEmisor == null) {
            $qb->join("proforma.establecimiento", "establecimiento");
            $qb->where('establecimiento.id = :idEstablecimiento');
            $qb->setParameter("idEstablecimiento", $idEstablecimiento);
        } else {
            $qb->join("proforma.emisor", "emisor");
            $qb->where('emisor.id = :idEmisor');
            $qb->setParameter("idEmisor", $idEmisor);
        }

        try {
            return $qb->getQuery()->getSingleScalarResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return 0;
        }
    }

    public function findProformas($search, $start, $limit, $idEstablecimiento, $idEmisor) {
        $datos = explode("&", $search);
        $fechaInicial = "";
        $fechaFinal = "";
        if (count($datos) == 3) {
            $search = $datos[2];
            $fechaInicial = $datos[0];
            $fechaFinal = $datos[1];
        }

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select("proforma, cliente")
                ->from("FactelBundle:Proforma", "proforma")
                ->join("proforma.emisor", "emisor")
                ->join("proforma.establecimiento", "establecimiento")
                ->join("proforma.cliente", "cliente");
        $qb->setMaxResults($limit);
        $qb->setFirstResult($start);
        if ($search != "") {
            $qb->where(
                            $qb->expr()->like('proforma.estado', $qb->expr()->literal('%' . $search . '%'))
                    )
                    ->orWhere(
                            $qb->expr()->like('proforma.numero', $qb->expr()->literal('%' . $search . '%'))
                    )
                    ->orWhere(
                            $qb->expr()->like('cliente.nombre', $qb->expr()->literal('%' . $search . '%'))
                    )
                    ->orWhere(
                            'cliente.identificacion=:identificacion'
            );
            $qb->setParameter("identificacion", $search);
        }


        if ($idEmisor == null) {
            $qb->andWhere('establecimiento.id = :idEstablecimiento');
            $qb->setParameter("idEstablecimiento", $idEstablecimiento);
        } else {
            $qb->andWhere('emisor.id = :idEmisor');
            $qb->setParameter("idEmisor", $idEmisor);
        }

        if ($fechaInicial != "" && $fechaFinal) {
            $qb->andWhere("proforma.fechaEmision BETWEEN :fechaInicial AND :fechaFinal")
                    ->setParameter('fechaInicial', $fechaInicial)
                    ->setParameter('fechaFinal', $fechaFinal);
        }

        $qb->orderBy("proforma.numero", "DESC");
        return $qb->getQuery()->getResult();
    }

    public function findProformaById($id) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select("proforma, emisor,establecimiento, proformasHasProducto, producto, impuestos, cliente")
                ->from("FactelBundle:Proforma", "proforma")
                ->join("proforma.emisor", "emisor")
                ->join("proforma.establecimiento", "establecimiento")
                ->join("proforma.cliente", "cliente")
                ->join("proforma.proformasHasProducto", "proformasHasProducto")
                ->join("proformasHasProducto.producto", "producto")
                ->join("proformasHasProducto.impuestos", "impuestos")
                ->where('proforma.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
