<?php

namespace FactelBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository {

    public function findRolesNoAdmin() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select("role")
                ->from("FactelBundle:Role", "role");

        return $qb->getQuery()->getResult();
    }

}
